import {
  User,
  ConstructionObject,
  MaterialItem,
  MechanismItem,
  MaterialZayavka,
  TechReport,
  UmmZayavka,
  PmuZayavka,
  PmuIzdeliyeNakladnoy,
  Nakladnoy,
  StockBalance,
  AccountInvoice,
  MaterialSynonymMapping,
  ActivityLog,
  BackupRecord,
} from '@/types/stroy';

export const INITIAL_MATERIALS: MaterialItem[] = [
  { id: 'mat-1', code: 'M-101', name: 'Арматура А500С Ø12 мм', unit: 'тн', category: 'metal', standardPrice: 9400000 },
  { id: 'mat-2', code: 'M-102', name: 'Арматура А500С Ø16 мм', unit: 'тн', category: 'metal', standardPrice: 9500000 },
  { id: 'mat-3', code: 'M-103', name: 'Арматура А500С Ø20 мм', unit: 'тн', category: 'metal', standardPrice: 9650000 },
  { id: 'mat-4', code: 'M-104', name: 'Катанка Ø6.5 мм', unit: 'тн', category: 'metal', standardPrice: 8900000 },
  { id: 'mat-5', code: 'M-201', name: 'Цемент ПЦ 400 Д20', unit: 'тн', category: 'cement', standardPrice: 820000 },
  { id: 'mat-6', code: 'M-202', name: 'Цемент М500 (қопларда 50кг)', unit: 'тн', category: 'cement', standardPrice: 980000 },
  { id: 'mat-7', code: 'M-301', name: 'Бетон товарный B20 (M250)', unit: 'м³', category: 'concrete', standardPrice: 580000 },
  { id: 'mat-8', code: 'M-302', name: 'Бетон товарный B25 (M350)', unit: 'м³', category: 'concrete', standardPrice: 650000 },
  { id: 'mat-9', code: 'M-401', name: 'Кирпич жжёный одинарный 1НФ', unit: 'дона', category: 'brick', standardPrice: 1650 },
  { id: 'mat-10', code: 'M-402', name: 'Пеноблок 600x300x200 D600', unit: 'м³', category: 'brick', standardPrice: 720000 },
  { id: 'mat-11', code: 'M-501', name: 'Песок мытый фр. 0-5 мм', unit: 'м³', category: 'other', standardPrice: 110000 },
  { id: 'mat-12', code: 'M-502', name: 'Щебень гранитный фр. 5-20 мм', unit: 'м³', category: 'other', standardPrice: 160000 },
  { id: 'mat-13', code: 'M-601', name: 'Труба профильная 80x80x4 мм', unit: 'п/м', category: 'pipes', standardPrice: 125000 },
  { id: 'mat-14', code: 'M-602', name: 'Труба стальная ДУ-50', unit: 'п/м', category: 'pipes', standardPrice: 85000 },
  { id: 'mat-15', code: 'M-701', name: 'Профнастил Н-60 (0.7 мм оцинк)', unit: 'м²', category: 'metal', standardPrice: 92000 },
  { id: 'mat-16', code: 'M-801', name: 'Пеноплекс Комфорт 50 мм', unit: 'м³', category: 'insulation', standardPrice: 680000 },
  { id: 'mat-17', code: 'M-802', name: 'Минеральная вата Isover 100 мм', unit: 'м²', category: 'insulation', standardPrice: 48000 },
  { id: 'mat-18', code: 'M-901', name: 'Эмаль ПФ-115 серая (20 кг)', unit: 'кг', category: 'paint', standardPrice: 38000 },
];

export const INITIAL_MECHANISMS: MechanismItem[] = [
  { id: 'mech-1', code: 'UMM-01', name: 'Автокран Liebherr LTM 1050 (50т)', type: 'Кран', plateNumber: '01 777 UMM', org: 'УММ', status: 'available' },
  { id: 'mech-2', code: 'UMM-02', name: 'Автокран XCMG QY25K5 (25т)', type: 'Кран', plateNumber: '01 412 UMM', org: 'УММ', status: 'in_use' },
  { id: 'mech-3', code: 'UMM-03', name: 'Экскаватор гусеничный Hyundai R220LC-9S', type: 'Экскаватор', plateNumber: '01 320 UMM', org: 'УММ', status: 'available' },
  { id: 'mech-4', code: 'UMM-04', name: 'Самосвал KAMAZ 6520 (20т)', type: 'Самосвал', plateNumber: '01 555 UMM', org: 'УММ', status: 'available' },
  { id: 'mech-5', code: 'UMM-05', name: 'Автобетононасос Putzmeister 36м', type: 'Бетононасос', plateNumber: '01 888 UMM', org: 'УММ', status: 'in_use' },
  { id: 'mech-6', code: 'UMM-06', name: 'Бульдозер Shantui SD16', type: 'Бульдозер', plateNumber: '01 109 UMM', org: 'УММ', status: 'available' },
];

export const INITIAL_OBJECTS: ConstructionObject[] = [
  {
    id: 'obj-101',
    code: 'OBJ-101',
    name: '101-Объект: Яшнаобод МФЙ 16-қаватли ТЖМ',
    org: 'РМУ',
    address: 'Тошкент ш., Яшнаобод тумани, Паркент кўчаси 12',
    prorabId: 'usr-prorab-rmu',
    status: 'active',
    startDate: '2025-11-01',
    endDate: '2026-12-30',
  },
  {
    id: 'obj-102',
    code: 'OBJ-102',
    name: '102-Объект: Олмазор 330-ўринли болалар боғчаси',
    org: 'РМУ',
    address: 'Тошкент ш., Олмазор тумани, Қорақаamish 2/4',
    prorabId: 'usr-prorab-rmu',
    status: 'active',
    startDate: '2026-02-15',
  },
  {
    id: 'obj-201',
    code: 'OBJ-201',
    name: '201-Объект: Чилонзор 990-ўринли замонавий мактаб',
    org: 'СМУ',
    address: 'Тошкент ш., Чилонзор 19-мавзе',
    prorabId: 'usr-prorab-smu',
    status: 'active',
    startDate: '2026-01-10',
  },
  {
    id: 'obj-301',
    code: 'OBJ-301',
    name: '301-Объект: Сергели магистрал кўприк эстакадаси',
    org: 'СУ',
    address: 'Тошкент ш., Сергели Қипчоқ кўчаси кесишмаси',
    prorabId: 'usr-prorab-su',
    status: 'active',
    startDate: '2025-08-01',
  },
  {
    id: 'obj-401',
    code: 'OBJ-401',
    name: '401-Объект: ПМУ Металлоконструкция ишлаб чиқариш цехи',
    org: 'ПМУ',
    address: 'Тошкент вил., Зангиота саноат зонаси 4',
    prorabId: 'usr-prorab-pmu',
    status: 'active',
    startDate: '2025-05-10',
  },
];

export const INITIAL_USERS: User[] = [
  // 1. ADMIN
  {
    id: 'usr-admin',
    login: 'admin',
    fullName: 'Исмоилов Дилшод Бахтиёрович',
    role: 'admin',
    roleTitleUz: 'Тизим администратори',
    roleTitleRu: 'Администратор системы',
    org: 'СО',
    phone: '+998 90 100-00-01',
  },
  // 2. PRORAB (RMU)
  {
    id: 'usr-prorab-rmu',
    login: 'prorab_rmu',
    fullName: 'Раҳимов Азиз Муродович (Прораб РМУ)',
    role: 'prorab',
    roleTitleUz: 'Майдон бошлиғи (Прораб)',
    roleTitleRu: 'Прораб / Начальник участка',
    org: 'РМУ',
    objId: 'obj-101',
    phone: '+998 93 511-22-33',
  },
  // PRORAB SMU
  {
    id: 'usr-prorab-smu',
    login: 'prorab_smu',
    fullName: 'Каримов Жасур Алиевич (Прораб СМУ)',
    role: 'prorab',
    roleTitleUz: 'Майдон бошлиғи (Прораб)',
    roleTitleRu: 'Прораб СМУ',
    org: 'СМУ',
    objId: 'obj-201',
    phone: '+998 94 622-33-44',
  },
  // 3. GLINJ_UPR (RMU)
  {
    id: 'usr-glinj-rmu',
    login: 'glinj_rmu',
    fullName: 'Умаров Шуҳрат Қосимович (Бош инж. РМУ)',
    role: 'glinj_upr',
    roleTitleUz: 'Бош муҳандис (РМУ)',
    roleTitleRu: 'Главный инженер управления (РМУ)',
    org: 'РМУ',
    phone: '+998 90 333-44-55',
  },
  // 4. NACH_UPR (RMU)
  {
    id: 'usr-nach-rmu',
    login: 'nach_rmu',
    fullName: 'Алиев Баҳодир Тўлқинович (Нач. РМУ)',
    role: 'nach_upr',
    roleTitleUz: 'Бошқарма бошлиғи (РМУ)',
    roleTitleRu: 'Начальник управления (РМУ)',
    org: 'РМУ',
    phone: '+998 97 777-11-22',
  },
  // 5. PTO_UPR (RMU)
  {
    id: 'usr-pto-rmu',
    login: 'pto_rmu',
    fullName: 'Маҳмудов Отабек Иброҳимович (ПТО РМУ)',
    role: 'pto_upr',
    roleTitleUz: 'ПТО муҳандиси (РМУ)',
    roleTitleRu: 'Инженер ПТО управления',
    org: 'РМУ',
    phone: '+998 91 222-33-44',
  },
  // 6. BUH_UPR (RMU)
  {
    id: 'usr-buh-rmu',
    login: 'buh_rmu',
    fullName: 'Турсунова Гулнора Саидовна (Бухг. РМУ)',
    role: 'buh_upr',
    roleTitleUz: 'Бошқарма бухгалтери (РМУ)',
    roleTitleRu: 'Бухгалтер управления (РМУ)',
    org: 'РМУ',
    phone: '+998 99 888-77-66',
  },
  // 7. PTO_SO (Markaziy PTO)
  {
    id: 'usr-pto-so',
    login: 'pto_so',
    fullName: 'Юлдашев Фарҳод Анварович (Бош ПТО СО)',
    role: 'pto_so',
    roleTitleUz: 'Бош ПТО бошлиғи (СО)',
    roleTitleRu: 'Начальник Главного ПТО (СО)',
    org: 'СО',
    phone: '+998 90 999-00-11',
  },
  // 8. GLINJ_SO (Markaziy Bosh Muhandis)
  {
    id: 'usr-glinj-so',
    login: 'glinj_so',
    fullName: 'Холматов Рустам Закирович (Бош инж. СО)',
    role: 'glinj_so',
    roleTitleUz: 'Компания Бош муҳандиси (СО)',
    roleTitleRu: 'Главный инженер компании (СО)',
    org: 'СО',
    phone: '+998 90 123-45-67',
  },
  // 9. SNAB_SO (Markaziy Ta'minot)
  {
    id: 'usr-snab-so',
    login: 'snab_so',
    fullName: 'Собиров Комил Эркинович (Таъминот СО)',
    role: 'snab_so',
    roleTitleUz: 'Марказий таъминот бошлиғи (СО)',
    roleTitleRu: 'Начальник снабжения (СО)',
    org: 'СО',
    phone: '+998 93 456-78-90',
  },
  // 10. SNAB (Ekspeditor)
  {
    id: 'usr-snab-exp',
    login: 'snab_exp',
    fullName: 'Норматов Сардор (Экспедитор)',
    role: 'snab',
    roleTitleUz: 'Экспедитор (Етказиб берувчи)',
    roleTitleRu: 'Экспедитор снабжения',
    org: 'РМУ',
    phone: '+998 94 111-22-33',
  },
  // 11. GLSKLAD (Markaziy Ombor)
  {
    id: 'usr-glsklad',
    login: 'glsklad',
    fullName: 'Қодиров Бахтиёр (Бош омборчи)',
    role: 'glsklad',
    roleTitleUz: 'Марказий омбор мудири',
    roleTitleRu: 'Заведующий главным складом',
    org: 'СО',
    phone: '+998 90 765-43-21',
  },
  // 12. RUK (Rahbariyat)
  {
    id: 'usr-ruk',
    login: 'ruk',
    fullName: 'Мирзаев Акмал Шухратович (Раҳбарият)',
    role: 'ruk',
    roleTitleUz: 'Бош директор / Раҳбарият',
    roleTitleRu: 'Руководство компании',
    org: 'СО',
    phone: '+998 90 999-99-99',
  },
  // 13. BUH_SO
  {
    id: 'usr-buh-so',
    login: 'buh_so',
    fullName: 'Абдуллаева Нигора (Бош бухгалтер СО)',
    role: 'buh_so',
    roleTitleUz: 'Бош бухгалтер (СО)',
    roleTitleRu: 'Главный бухгалтер (СО)',
    org: 'СО',
    phone: '+998 90 222-11-00',
  },
  // 14. DISPATCHER_PMU
  {
    id: 'usr-disp-pmu',
    login: 'disp_pmu',
    fullName: 'Шокиров Улуғбек (Диспетчер ПМУ)',
    role: 'dispatcher',
    roleTitleUz: 'ПМУ Диспетчери',
    roleTitleRu: 'Диспетчер ПМУ',
    org: 'ПМУ',
    phone: '+998 91 555-44-33',
  },
  // 15. KONSTRUKTOR_PMU
  {
    id: 'usr-konstr-pmu',
    login: 'konstr_pmu',
    fullName: 'Зокиров Ҳамид (Конструктор ПМУ)',
    role: 'konstruktor',
    roleTitleUz: 'Конструктор (ПМУ)',
    roleTitleRu: 'Инженер-конструктор ПМУ',
    org: 'ПМУ',
    phone: '+998 93 777-66-55',
  },
  // 16. DISPATCHER_UMM
  {
    id: 'usr-disp-umm',
    login: 'disp_umm',
    fullName: 'Бозоров Темур (Диспетчер УММ)',
    role: 'dispatcher_umm',
    roleTitleUz: 'УММ Диспетчери (Техника)',
    roleTitleRu: 'Диспетчер УММ (Механизмы)',
    org: 'УММ',
    phone: '+998 94 999-88-77',
  },
  // 17. SKLAD (Boshqarma omborchisi)
  {
    id: 'usr-sklad-rmu',
    login: 'sklad_rmu',
    fullName: 'Салимов Достон (Омборчи РМУ)',
    role: 'sklad',
    roleTitleUz: 'Бошқарма омборчиси',
    roleTitleRu: 'Кладовщик управления',
    org: 'РМУ',
    phone: '+998 90 444-55-66',
  },
];

export const INITIAL_ZAYAVKAS: MaterialZayavka[] = [
  {
    id: 'zy-2026-001',
    number: 'ЗМ-001/26',
    objId: 'obj-101',
    objName: '101-Объект: Яшнаобод МФЙ 16-қаватли ТЖМ',
    org: 'РМУ',
    authorId: 'usr-prorab-rmu',
    authorName: 'Раҳимов Азиз (Прораб РМУ)',
    createdAt: '2026-08-20 09:30',
    updatedAt: '2026-08-20 09:30',
    status: 'glinj_upr',
    urgency: 'normal',
    positions: [
      { id: 'pos-1', materialId: 'mat-1', materialName: 'Арматура А500С Ø12 мм', unit: 'тн', requestedQty: 15, approvedQty: 15, ptoChecked: false },
      { id: 'pos-2', materialId: 'mat-2', materialName: 'Арматура А500С Ø16 мм', unit: 'тн', requestedQty: 25, approvedQty: 25, ptoChecked: false },
      { id: 'pos-3', materialId: 'mat-5', materialName: 'Цемент ПЦ 400 Д20', unit: 'тн', requestedQty: 40, approvedQty: 40, ptoChecked: false },
    ],
    signatures: {},
    history: [
      { action: 'create', performedBy: 'Раҳимов Азиз', role: 'Прораб', timestamp: '2026-08-20 09:30', comment: 'Янги монолит блоки учун за miljø' },
    ],
  },
  {
    id: 'zy-2026-002',
    number: 'ЗМ-002/26',
    objId: 'obj-101',
    objName: '101-Объект: Яшнаобод МФЙ 16-қаватли ТЖМ',
    org: 'РМУ',
    authorId: 'usr-prorab-rmu',
    authorName: 'Раҳимов Азиз (Прораб РМУ)',
    createdAt: '2026-08-18 14:15',
    updatedAt: '2026-08-19 11:20',
    status: 'pto_so',
    urgency: 'urgent',
    positions: [
      { id: 'pos-4', materialId: 'mat-8', materialName: 'Бетон товарный B25 (M350)', unit: 'м³', requestedQty: 120, approvedQty: 120, ptoChecked: true, ptoNote: 'Норма бўйича тасдиқланди' },
      { id: 'pos-5', materialId: 'mat-4', materialName: 'Катанка Ø6.5 мм', unit: 'тн', requestedQty: 4, approvedQty: 3.5, ptoChecked: true, ptoNote: '0.5 тн қолдиқ ҳисобига камайтирилди' },
    ],
    signatures: {
      glinj_upr: { name: 'Умаров Шуҳрат (Бош инж. РМУ)', date: '2026-08-19 11:20', role: 'glinj_upr' },
    },
    history: [
      { action: 'create', performedBy: 'Раҳимов Азиз', role: 'Прораб', timestamp: '2026-08-18 14:15' },
      { action: 'approve_glinj_upr', performedBy: 'Умаров Шуҳрат', role: 'Бош муҳандис РМУ', timestamp: '2026-08-19 11:20', comment: 'Ҳажмлар текширилди' },
    ],
  },
  {
    id: 'zy-2026-003',
    number: 'ЗМ-003/26',
    objId: 'obj-201',
    objName: '201-Объект: Чилонзор 990-ўринли замонавий мактаб',
    org: 'СМУ',
    authorId: 'usr-prorab-smu',
    authorName: 'Каримов Жасур (Прораб СМУ)',
    createdAt: '2026-08-15 10:00',
    updatedAt: '2026-08-17 16:45',
    status: 'snab_so',
    urgency: 'normal',
    positions: [
      { id: 'pos-6', materialId: 'mat-9', materialName: 'Кирпич жжёный одинарный 1НФ', unit: 'дона', requestedQty: 35000, approvedQty: 35000, ptoChecked: true },
      { id: 'pos-7', materialId: 'mat-11', materialName: 'Песок мытый фр. 0-5 мм', unit: 'м³', requestedQty: 60, approvedQty: 60, ptoChecked: true },
    ],
    signatures: {
      glinj_upr: { name: 'Каримов И. (Бош инж. СМУ)', date: '2026-08-16 09:30', role: 'glinj_upr' },
      pto_so: { name: 'Юлдашев Фарҳод (Бош ПТО СО)', date: '2026-08-16 15:10', note: 'Лойиҳа ҳажмига мувофиқ' },
      glinj_so: { name: 'Холматов Рустам (Бош инж. СО)', date: '2026-08-17 16:45' },
    },
    history: [
      { action: 'create', performedBy: 'Каримов Жасур', role: 'Прораб СМУ', timestamp: '2026-08-15 10:00' },
      { action: 'approve_glinj_upr', performedBy: 'Каримов И.', role: 'Бош инж. СМУ', timestamp: '2026-08-16 09:30' },
      { action: 'approve_pto_so', performedBy: 'Юлдашев Фарҳод', role: 'Бош ПТО СО', timestamp: '2026-08-16 15:10' },
      { action: 'approve_glinj_so', performedBy: 'Холматов Рустам', role: 'Бош инж. СО', timestamp: '2026-08-17 16:45' },
    ],
  },
  {
    id: 'zy-2026-004',
    number: 'ЗМ-004/26',
    objId: 'obj-101',
    objName: '101-Объект: Яшнаобод МФЙ 16-қаватли ТЖМ',
    org: 'РМУ',
    authorId: 'usr-prorab-rmu',
    authorName: 'Раҳимов Азиз (Прораб РМУ)',
    createdAt: '2026-08-10 08:30',
    updatedAt: '2026-08-12 14:00',
    status: 'completed',
    urgency: 'normal',
    contractNo: 'ДОГ-448/РМУ',
    contractDate: '2026-08-12',
    invoiceFile: {
      name: 'Schet_Faktura_Armatura_448.pdf',
      size: '1.4 MB',
      uploadedAt: '2026-08-12 14:00',
    },
    positions: [
      { id: 'pos-8', materialId: 'mat-3', materialName: 'Арматура А500С Ø20 мм', unit: 'тн', requestedQty: 30, approvedQty: 30, ptoChecked: true },
    ],
    signatures: {
      glinj_upr: { name: 'Умаров Шуҳрат', date: '2026-08-10 11:00', role: 'glinj_upr' },
      pto_so: { name: 'Юлдашев Фарҳод', date: '2026-08-11 10:20' },
      glinj_so: { name: 'Холматов Рустам', date: '2026-08-11 17:00' },
      snab_so: { name: 'Собиров Комил', date: '2026-08-12 14:00', contractNo: 'ДОГ-448/РМУ', contractDate: '2026-08-12', invoiceFileName: 'Schet_Faktura_Armatura_448.pdf' },
    },
  },
];

export const INITIAL_TECH_REPORTS: TechReport[] = [
  {
    id: 'tr-2026-07',
    number: 'TH-07/26-101',
    month: '2026-07',
    monthName: 'Июль 2026',
    objId: 'obj-101',
    objName: '101-Объект: Яшнаобод МФЙ 16-қаватли ТЖМ',
    org: 'РМУ',
    authorId: 'usr-prorab-rmu',
    authorName: 'Раҳимов Азиз (Прораб РМУ)',
    createdAt: '2026-08-01 10:00',
    status: 'listed',
    rows: [
      { id: 'tr-r1', materialId: 'mat-1', materialName: 'Арматура А500С Ø12 мм', unit: 'тн', normQty: 18.5, factQty: 18.2, spisanieQty: 18.2, differenceQty: 0, note: 'Монолит устунлар' },
      { id: 'tr-r2', materialId: 'mat-8', materialName: 'Бетон товарный B25 (M350)', unit: 'м³', normQty: 150, factQty: 148, spisanieQty: 148, differenceQty: 0, note: '4-қават плитаси' },
      { id: 'tr-r3', materialId: 'mat-5', materialName: 'Цемент ПЦ 400 Д20', unit: 'тн', normQty: 25, factQty: 24.5, spisanieQty: 24.0, differenceQty: -0.5, note: 'Тежамкорлик эвазига 0.5т иқтисод' },
    ],
    signatures: {
      prorab: { name: 'Раҳимов Азиз Муродович', date: '2026-08-01 10:00' },
      pto_upr: { name: 'Маҳмудов Отабек (ПТО РМУ)', date: '2026-08-02 14:30' },
      buh_upr: { name: 'Турсунова Гулнора (Бухг. РМУ)', date: '2026-08-03 11:15' },
      glinj_upr: { name: 'Умаров Шуҳрат (Бош инж. РМУ)', date: '2026-08-04 16:40' },
    },
  },
  {
    id: 'tr-2026-08',
    number: 'TH-08/26-101',
    month: '2026-08',
    monthName: 'Август 2026',
    objId: 'obj-101',
    objName: '101-Объект: Яшнаобод МФЙ 16-қаватли ТЖМ',
    org: 'РМУ',
    authorId: 'usr-prorab-rmu',
    authorName: 'Раҳимов Азиз (Прораб РМУ)',
    createdAt: '2026-08-22 15:30',
    status: 'pto',
    rows: [
      { id: 'tr-r4', materialId: 'mat-1', materialName: 'Арматура А500С Ø12 мм', unit: 'тн', normQty: 22.0, factQty: 21.8, spisanieQty: 0, differenceQty: 0, note: '5-қават устунлари' },
      { id: 'tr-r5', materialId: 'mat-2', materialName: 'Арматура А500С Ø16 мм', unit: 'тн', normQty: 30.0, factQty: 29.5, spisanieQty: 0, differenceQty: 0, note: 'Ригель ва тўсинлар' },
      { id: 'tr-r6', materialId: 'mat-8', materialName: 'Бетон товарный B25 (M350)', unit: 'м³', normQty: 210, factQty: 212, spisanieQty: 0, differenceQty: 0, note: 'Подавал ва 5-қават' },
      { id: 'tr-r7', materialId: 'mat-9', materialName: 'Кирпич жжёный одинарный 1НФ', unit: 'дона', normQty: 45000, factQty: 44200, spisanieQty: 0, differenceQty: 0, note: '3-қават деворлари' },
    ],
    signatures: {
      prorab: { name: 'Раҳимов Азиз Муродович', date: '2026-08-22 15:30' },
    },
  },
];

export const INITIAL_UMM_ZAYAVKAS: UmmZayavka[] = [
  {
    id: 'umm-001',
    number: 'УММ-012/26',
    objId: 'obj-101',
    objName: '101-Объект: Яшнаобод МФЙ 16-қаватли ТЖМ',
    org: 'РМУ',
    authorId: 'usr-prorab-rmu',
    authorName: 'Раҳимов Азиз (Прораб РМУ)',
    targetDate: '2026-08-26',
    targetWorkDescription: '5-қават монолит плитасини қуйиш учун автобетононасос ва опалубкаларни кўтариш учун 25т автокран',
    requestedMechanisms: [
      { mechanismType: 'Автокран 25т', count: 1, hours: 8, notes: 'Опалубка кўтаришга' },
      { mechanismType: 'Автобетононасос 36м+', count: 1, hours: 10, notes: '210 м³ бетон уриш' },
    ],
    assignedMechanisms: [
      { mechanismId: 'mech-2', mechanismName: 'Автокран XCMG QY25K5 (25т)', plateNumber: '01 412 UMM', driverName: 'Искандаров А.', startTime: '08:00', endTime: '17:00', shiftHours: 8 },
      { mechanismId: 'mech-5', mechanismName: 'Автобетононасос Putzmeister 36м', plateNumber: '01 888 UMM', driverName: 'Ҳасанов Б.', startTime: '07:30', endTime: '18:00', shiftHours: 10 },
    ],
    status: 'umm',
    createdAt: '2026-08-22 11:00',
    signatures: {
      upr_head: { name: 'Умаров Шуҳрат (Бош инж. РМУ)', role: 'glinj_upr', date: '2026-08-22 14:15' },
      glinj_so: { name: 'Холматов Рустам (Бош инж. СО)', date: '2026-08-23 09:30' },
    },
  },
  {
    id: 'umm-002',
    number: 'УММ-013/26',
    objId: 'obj-201',
    objName: '201-Объект: Чилонзор 990-ўринли замонавий мактаб',
    org: 'СМУ',
    authorId: 'usr-prorab-smu',
    authorName: 'Каримов Жасур (Прораб СМУ)',
    targetDate: '2026-08-28',
    targetWorkDescription: 'Котлован қазиш ва тупроқни ташиб чиқариш ишлари',
    requestedMechanisms: [
      { mechanismType: 'Экскаватор гусеничный', count: 1, hours: 8 },
      { mechanismType: 'Самосвал 20т', count: 3, hours: 8 },
    ],
    status: 'glinj_so',
    createdAt: '2026-08-24 08:45',
    signatures: {
      upr_head: { name: 'Каримов И. (Бош инж. СМУ)', role: 'glinj_upr', date: '2026-08-24 10:20' },
    },
  },
];

export const INITIAL_PMU_ZAYAVKAS: PmuZayavka[] = [
  {
    id: 'pmu-001',
    number: 'ПМУ-005/26',
    objId: 'obj-101',
    objName: '101-Объект: Яшнаобод МФЙ 16-қаватли ТЖМ',
    org: 'РМУ',
    authorId: 'usr-prorab-rmu',
    authorName: 'Раҳимов Азиз (Прораб РМУ)',
    structureName: 'Металл том фермаси 18м (ФМ-18)',
    category: 'metal_ferma',
    quantity: 12,
    unit: 'дона',
    technicalSpecs: 'ГОСТ 23118-2019 бўйича. 09Г2С пўлат, грунтовка ГФ-021 билан 2 қават қопланган.',
    drawingFile: {
      name: 'Chizma_Ferma_FM18_Rev2.pdf',
      size: '1.8 MB',
      type: 'application/pdf',
      uploadedAt: '2026-08-21 16:30',
    },
    status: 'pmu',
    createdAt: '2026-08-21 16:30',
    signatures: {
      upr_head: { name: 'Умаров Шуҳрат (Бош инж. РМУ)', role: 'glinj_upr', date: '2026-08-22 10:00' },
      pto_so: { name: 'Юлдашев Фарҳод (Бош ПТО СО)', date: '2026-08-22 15:45' },
      glinj_so: { name: 'Холматов Рустам (Бош инж. СО)', date: '2026-08-23 11:20' },
    },
  },
  {
    id: 'pmu-002',
    number: 'ПМУ-006/26',
    objId: 'obj-301',
    objName: '301-Объект: Сергели магистрал кўприк эстакадаси',
    org: 'СУ',
    authorId: 'usr-prorab-su',
    authorName: 'Эргашев Дилшод (Прораб СУ)',
    structureName: 'Кўприк оралиқ ригели РК-24',
    category: 'balka',
    quantity: 8,
    unit: 'дона',
    technicalSpecs: 'Оғир конструкция, КМД 14-сонли чизма асосида.',
    drawingFile: {
      name: 'Rigel_RK24_KMD.dwg',
      size: '1.95 MB',
      type: 'application/dwg',
      uploadedAt: '2026-08-24 11:15',
    },
    status: 'upr',
    createdAt: '2026-08-24 11:15',
    signatures: {},
  },
];

export const INITIAL_PMU_IZDELIYE_NAKLADNOY: PmuIzdeliyeNakladnoy[] = [
  {
    id: 'pmu-nak-01',
    number: 'ИН-04/ПМУ-26',
    pmuZayavkaId: 'pmu-001',
    structureName: 'Металл том фермаси 18м (ФМ-18) [1-партия]',
    quantity: 6,
    unit: 'дона',
    objId: 'obj-101',
    objName: '101-Объект: Яшнаобод МФЙ 16-қаватли ТЖМ',
    prorabId: 'usr-prorab-rmu',
    prorabName: 'Раҳимов Азиз (Прораб РМУ)',
    konstruktorId: 'usr-konstr-pmu',
    konstruktorName: 'Зокиров Ҳамид (Конструктор ПМУ)',
    status: 'sent',
    sentDate: '2026-08-24 14:00',
    notes: 'ПМУ цехида синовдан ўтган, паспорт ва сертификат илова қилинди.',
  },
];

export const INITIAL_NAKLADNOYS: Nakladnoy[] = [
  {
    id: 'nak-101',
    number: 'Н-142/26',
    fromOwnerType: 'admin',
    fromOwnerId: 'usr-glsklad',
    fromOwnerName: 'Марказий омбор (СО)',
    toOwnerType: 'prorab',
    toOwnerId: 'usr-prorab-rmu',
    toOwnerName: 'Раҳимов Азиз (Прораб РМУ)',
    toObjId: 'obj-101',
    toObjName: '101-Объект: Яшнаобод МФЙ 16-қаватли ТЖМ',
    status: 'sent',
    createdAt: '2026-08-24 12:30',
    carrierDriver: 'Норматов Сардор (Экспедитор)',
    carPlateNumber: '01 944 AAA',
    items: [
      { materialId: 'mat-1', materialName: 'Арматура А500С Ø12 мм', unit: 'тн', qty: 10, price: 9400000 },
      { materialId: 'mat-5', materialName: 'Цемент ПЦ 400 Д20', unit: 'тн', qty: 15, price: 820000 },
    ],
  },
  {
    id: 'nak-102',
    number: 'Н-138/26',
    fromOwnerType: 'admin',
    fromOwnerId: 'usr-glsklad',
    fromOwnerName: 'Марказий омбор (СО)',
    toOwnerType: 'prorab',
    toOwnerId: 'usr-prorab-rmu',
    toOwnerName: 'Раҳимов Азиз (Прораб РМУ)',
    toObjId: 'obj-101',
    toObjName: '101-Объект: Яшнаобод МФЙ 16-қаватли ТЖМ',
    status: 'approved',
    createdAt: '2026-08-18 09:00',
    approvedAt: '2026-08-18 15:40',
    carrierDriver: 'Содиқов М.',
    carPlateNumber: '01 512 BBB',
    items: [
      { materialId: 'mat-9', materialName: 'Кирпич жжёный одинарный 1НФ', unit: 'дона', qty: 20000, price: 1650 },
      { materialId: 'mat-11', materialName: 'Песок мытый фр. 0-5 мм', unit: 'м³', qty: 40, price: 110000 },
    ],
  },
];

export const INITIAL_STOCKS: StockBalance[] = [
  // 1. Markaziy Ombor (Admin)
  { id: 'stk-1', ownerType: 'admin', ownerId: 'usr-glsklad', ownerName: 'Марказий омбор (СО)', org: 'СО', materialId: 'mat-1', materialName: 'Арматура А500С Ø12 мм', unit: 'тн', category: 'metal', qty: 85.5, lastUpdated: '2026-08-24' },
  { id: 'stk-2', ownerType: 'admin', ownerId: 'usr-glsklad', ownerName: 'Марказий омбор (СО)', org: 'СО', materialId: 'mat-2', materialName: 'Арматура А500С Ø16 мм', unit: 'тн', category: 'metal', qty: 62.0, lastUpdated: '2026-08-24' },
  { id: 'stk-3', ownerType: 'admin', ownerId: 'usr-glsklad', ownerName: 'Марказий омбор (СО)', org: 'СО', materialId: 'mat-5', materialName: 'Цемент ПЦ 400 Д20', unit: 'тн', category: 'cement', qty: 140.0, lastUpdated: '2026-08-24' },
  { id: 'stk-4', ownerType: 'admin', ownerId: 'usr-glsklad', ownerName: 'Марказий омбор (СО)', org: 'СО', materialId: 'mat-9', materialName: 'Кирпич жжёный одинарный 1НФ', unit: 'дона', category: 'brick', qty: 120000, lastUpdated: '2026-08-24' },
  { id: 'stk-5', ownerType: 'admin', ownerId: 'usr-glsklad', ownerName: 'Марказий омбор (СО)', org: 'СО', materialId: 'mat-11', materialName: 'Песок мытый фр. 0-5 мм', unit: 'м³', category: 'other', qty: 320, lastUpdated: '2026-08-24' },
  { id: 'stk-6', ownerType: 'admin', ownerId: 'usr-glsklad', ownerName: 'Марказий омбор (СО)', org: 'СО', materialId: 'mat-15', materialName: 'Профнастил Н-60 (0.7 мм оцинк)', unit: 'м²', category: 'metal', qty: 850, lastUpdated: '2026-08-24' },

  // 2. Prorab RMU (Obj-101) Ombori
  { id: 'stk-10', ownerType: 'prorab', ownerId: 'usr-prorab-rmu', ownerName: 'Раҳимов Азиз (Прораб РМУ)', org: 'РМУ', objId: 'obj-101', materialId: 'mat-1', materialName: 'Арматура А500С Ø12 мм', unit: 'тн', category: 'metal', qty: 12.4, lastUpdated: '2026-08-24' },
  { id: 'stk-11', ownerType: 'prorab', ownerId: 'usr-prorab-rmu', ownerName: 'Раҳимов Азиз (Прораб РМУ)', org: 'РМУ', objId: 'obj-101', materialId: 'mat-2', materialName: 'Арматура А500С Ø16 мм', unit: 'тн', category: 'metal', qty: 18.0, lastUpdated: '2026-08-24' },
  { id: 'stk-12', ownerType: 'prorab', ownerId: 'usr-prorab-rmu', ownerName: 'Раҳимов Азиз (Прораб РМУ)', org: 'РМУ', objId: 'obj-101', materialId: 'mat-5', materialName: 'Цемент ПЦ 400 Д20', unit: 'тн', category: 'cement', qty: 22.5, lastUpdated: '2026-08-24' },
  { id: 'stk-13', ownerType: 'prorab', ownerId: 'usr-prorab-rmu', ownerName: 'Раҳимов Азиз (Прораб РМУ)', org: 'РМУ', objId: 'obj-101', materialId: 'mat-9', materialName: 'Кирпич жжёный одинарный 1НФ', unit: 'дона', category: 'brick', qty: 15400, lastUpdated: '2026-08-24' },

  // 3. Expeditor Ombori
  { id: 'stk-20', ownerType: 'expeditor', ownerId: 'usr-snab-exp', ownerName: 'Норматов Сардор (Экспедитор)', org: 'РМУ', materialId: 'mat-1', materialName: 'Арматура А500С Ø12 мм', unit: 'тн', category: 'metal', qty: 5.0, lastUpdated: '2026-08-24' },
  { id: 'stk-21', ownerType: 'expeditor', ownerId: 'usr-snab-exp', ownerName: 'Норматов Сардор (Экспедитор)', org: 'РМУ', materialId: 'mat-18', materialName: 'Эмаль ПФ-115 серая (20 кг)', unit: 'кг', category: 'paint', qty: 180, lastUpdated: '2026-08-24' },
];

export const INITIAL_ACCOUNT_INVOICES: AccountInvoice[] = [
  {
    id: 'acc-inv-01',
    invoiceNumber: 'СФ-8819/08',
    invoiceDate: '2026-08-14',
    supplierName: 'ООО «BEKABAD METALL SERVIS»',
    supplierInn: '304551234',
    totalSum: 188000000,
    org: 'РМУ',
    objId: 'obj-101',
    objName: '101-Объект: Яшнаобод МФЙ 16-қаватли ТЖМ',
    status: 'posted',
    importedAt: '2026-08-15 11:20',
    importedBy: 'Турсунова Гулнора (Бухг. РМУ)',
    items: [
      { rawMaterialName: 'Прокат арматурный периодического профиля кл. А500С д.12мм', matchedMaterialId: 'mat-1', matchedMaterialName: 'Арматура А500С Ø12 мм', unit: 'тн', qty: 20, price: 9400000, total: 188000000 },
    ],
  },
  {
    id: 'acc-inv-02',
    invoiceNumber: 'СФ-3410/08',
    invoiceDate: '2026-08-19',
    supplierName: 'СП АО «QIZILQUMTSEMENT»',
    supplierInn: '201998432',
    totalSum: 41000000,
    org: 'РМУ',
    objId: 'obj-101',
    objName: '101-Объект: Яшнаобод МФЙ 16-қаватли ТЖМ',
    status: 'verified',
    importedAt: '2026-08-20 16:10',
    importedBy: 'Турсунова Гулнора (Бухг. РМУ)',
    items: [
      { rawMaterialName: 'Портландцемент со шлаком ПЦ400-Д20 навалом', matchedMaterialId: 'mat-5', matchedMaterialName: 'Цемент ПЦ 400 Д20', unit: 'тн', qty: 50, price: 820000, total: 41000000 },
    ],
  },
];

export const INITIAL_SYNONYM_MAPPINGS: MaterialSynonymMapping[] = [
  {
    id: 'syn-1',
    rawSupplierName: 'Прокат арматурный периодического профиля кл. А500С д.12мм',
    canonicalMaterialId: 'mat-1',
    canonicalMaterialName: 'Арматура А500С Ø12 мм',
    org: 'РМУ',
    createdAt: '2026-08-15',
  },
  {
    id: 'syn-2',
    rawSupplierName: 'Портландцемент со шлаком ПЦ400-Д20 навалом',
    canonicalMaterialId: 'mat-5',
    canonicalMaterialName: 'Цемент ПЦ 400 Д20',
    org: 'РМУ',
    createdAt: '2026-08-20',
  },
  {
    id: 'syn-3',
    rawSupplierName: 'Смесь бетонная тяжелая БСГ В25 П4 F150 W6',
    canonicalMaterialId: 'mat-8',
    canonicalMaterialName: 'Бетон товарный B25 (M350)',
    createdAt: '2026-08-10',
  },
];

export const INITIAL_ACTIVITY_LOGS: ActivityLog[] = [
  {
    id: 'act-001',
    timestamp: '2026-08-24 14:00',
    userId: 'usr-konstr-pmu',
    userName: 'Зокиров Ҳамид',
    userRole: 'konstruktor',
    org: 'ПМУ',
    action: 'pmu_nakladnoy.create',
    entityType: 'pmu',
    entityId: 'pmu-nak-01',
    description: 'ПМУ тайёр маҳсулот юк хати (ИН-04/ПМУ-26) тузилди ва Прорабга жўнатилди',
  },
  {
    id: 'act-002',
    timestamp: '2026-08-24 12:30',
    userId: 'usr-glsklad',
    userName: 'Қодиров Бахтиёр',
    userRole: 'glsklad',
    org: 'СО',
    action: 'nakladnoy.create',
    entityType: 'nakladnoy',
    entityId: 'nak-101',
    description: 'Марказий омбордан 101-объектга Н-142/26 сонли юк хати юборилди',
  },
  {
    id: 'act-003',
    timestamp: '2026-08-24 11:15',
    userId: 'usr-prorab-su',
    userName: 'Эргашев Дилшод',
    userRole: 'prorab',
    org: 'СУ',
    action: 'pmu_zayavka.create',
    entityType: 'pmu',
    entityId: 'pmu-002',
    description: 'Янги ПМУ конструкция за miljøси яратилди (ПМУ-006/26)',
  },
  {
    id: 'act-004',
    timestamp: '2026-08-24 09:30',
    userId: 'usr-glinj-so',
    userName: 'Холматов Рустам',
    userRole: 'glinj_so',
    org: 'СО',
    action: 'zayavka.approve_glinj_so',
    entityType: 'zayavka',
    entityId: 'zy-2026-003',
    description: 'ЗМ-003/26 сонли моддий за miljø СО Бош муҳандиси томонидан тасдиқланди → Снабжение СО га ўтди',
  },
  {
    id: 'act-005',
    timestamp: '2026-08-24 08:30',
    userId: 'usr-admin',
    userName: 'Исмоилов Дилшод',
    userRole: 'admin',
    org: 'СО',
    action: 'backup.auto',
    entityType: 'backup',
    description: 'Режали 24-соатлик авто-захира нусхаси муваффақиятли яратилди (data/backups/auto-2026-08-24.json)',
  },
];

export const INITIAL_BACKUPS: BackupRecord[] = [
  {
    id: 'bk-2026-08-24',
    createdAt: '2026-08-24 08:30:00',
    type: 'auto',
    fileName: 'auto-backup-2026-08-24.json',
    sizeBytes: 84200,
    recordCounts: {
      zayavkas: 4,
      techReports: 2,
      umm: 2,
      pmu: 2,
      nakladnoy: 2,
      stocks: 12,
      activities: 5,
    },
  },
  {
    id: 'bk-2026-08-23',
    createdAt: '2026-08-23 08:30:00',
    type: 'auto',
    fileName: 'auto-backup-2026-08-23.json',
    sizeBytes: 81400,
    recordCounts: {
      zayavkas: 4,
      techReports: 2,
      umm: 2,
      pmu: 2,
      nakladnoy: 2,
      stocks: 12,
      activities: 4,
    },
  },
];
